/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _BOX2_H_RPCGEN
#define _BOX2_H_RPCGEN

#define RPCGEN_VERSION	199506

#include <rpc/rpc.h>


struct dimensions {
	float length;
	float width;
	float height;
};
typedef struct dimensions dimensions;
#ifdef __cplusplus
extern "C" bool_t xdr_dimensions(XDR *, dimensions*);
#elif __STDC__
extern  bool_t xdr_dimensions(XDR *, dimensions*);
#else /* Old Style C */
bool_t xdr_dimensions();
#endif /* Old Style C */


struct box_results {
	float volume;
	float surface;
};
typedef struct box_results box_results;
#ifdef __cplusplus
extern "C" bool_t xdr_box_results(XDR *, box_results*);
#elif __STDC__
extern  bool_t xdr_box_results(XDR *, box_results*);
#else /* Old Style C */
bool_t xdr_box_results();
#endif /* Old Style C */


struct mail_dims {
	float volume;
	float mass;
};
typedef struct mail_dims mail_dims;
#ifdef __cplusplus
extern "C" bool_t xdr_mail_dims(XDR *, mail_dims*);
#elif __STDC__
extern  bool_t xdr_mail_dims(XDR *, mail_dims*);
#else /* Old Style C */
bool_t xdr_mail_dims();
#endif /* Old Style C */


#define RPC_BOX ((rpc_uint)0x40049453)
#define BOXVERSION2 ((rpc_uint)2)

#ifdef __cplusplus
#define BOX_CALC ((rpc_uint)1)
extern "C" box_results * box_calc_2(dimensions *, CLIENT *);
extern "C" box_results * box_calc_2_svc(dimensions *, struct svc_req *);
#define MAIL_CALC ((rpc_uint)2)
extern "C" float * mail_calc_2(mail_dims *, CLIENT *);
extern "C" float * mail_calc_2_svc(mail_dims *, struct svc_req *);

#elif __STDC__
#define BOX_CALC ((rpc_uint)1)
extern  box_results * box_calc_2(dimensions *, CLIENT *);
extern  box_results * box_calc_2_svc(dimensions *, struct svc_req *);
#define MAIL_CALC ((rpc_uint)2)
extern  float * mail_calc_2(mail_dims *, CLIENT *);
extern  float * mail_calc_2_svc(mail_dims *, struct svc_req *);

#else /* Old Style C */
#define BOX_CALC ((rpc_uint)1)
extern  box_results * box_calc_2();
extern  box_results * box_calc_2_svc();
#define MAIL_CALC ((rpc_uint)2)
extern  float * mail_calc_2();
extern  float * mail_calc_2_svc();
#endif /* Old Style C */

#endif /* !_BOX2_H_RPCGEN */
