/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "box.h"

bool_t
xdr_dimensions(XDR *xdrs, dimensions *objp)
{

	if (!xdr_float(xdrs, &objp->length))
		return (FALSE);
	if (!xdr_float(xdrs, &objp->width))
		return (FALSE);
	if (!xdr_float(xdrs, &objp->height))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_box_results(XDR *xdrs, box_results *objp)
{

	if (!xdr_float(xdrs, &objp->volume))
		return (FALSE);
	if (!xdr_float(xdrs, &objp->surface))
		return (FALSE);
	return (TRUE);
}
